# Generated by Django 4.2.16 on 2024-10-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_message_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='AudioCall',
        ),
        migrations.DeleteModel(
            name='VideoCall',
        ),
    ]
