# Generated by Django 4.2.16 on 2024-09-20 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
