# Generated by Django 4.2.16 on 2024-10-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notifications_type_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
