# Generated by Django 4.2.16 on 2024-10-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useractivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
