# Generated by Django 4.2.16 on 2024-10-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_type',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('like', 'Like'), ('comment', 'Comment'), ('chat', 'Chat'), ('videocall', 'Videocall')], max_length=20),
        ),
    ]
